
# --- Core / Desktop Portal ---
exec-once = $scrPath/resetxdgportal.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# --- Authentication ---
exec-once = $scrPath/polkitkdeauth.sh

# --- Bar & Notifications ---
exec-once = waybar
exec-once = dunst
# exec-once = swaync

# --- System Tray ---
exec-once = blueman-applet
exec-once = udiskie --no-automount --smart-tray
exec-once = nm-applet --indicator

# --- Clipboard ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# --- Wallpaper & Misc ---
exec-once = $scrPath/swwwallpaper.sh
exec-once = $scrPath/batterynotify.sh
exec-once = awww-daemon
exec-once = hyprpm reload
