
#      ░▒▒▒░░░░░▓▓          ___________
#    ░░▒▒▒░░░░░▓▓        //___________/
#   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#       ░▒▓▓   ▓▓  //____/


# ── Global Variables ─────────────────────────────────────────
$scrPath = $HOME/.local/share/bin

permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
# ── Monitor ──────────────────────────────────────────────────
monitor = ,preferred,auto,auto


# ── Layouts ──────────────────────────────────────────────────
dwindle {
    # pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}



# ── Misc ─────────────────────────────────────────────────────
misc {
    # vfr = true
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
    force_zero_scaling = true
}


# ── Source Modules ───────────────────────────────────────────
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/plugins.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/themes/common.conf
# hyprlang noerror true
source = ~/.config/hypr/themes/theme.conf
# hyprlang noerror false
source = ~/.config/hypr/themes/colors.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/userprefs.conf
# Note: userprefs.conf is sourced last so it can override any setting above

# HyprMod managed settings
source = /home/ligichi/.config/hypr/hyprland-gui.conf
