
# █▀█ █░░ █░█ █▀▀ █ █▄░█ █▀
# █▀▀ █▄▄ █▄█ █▄█ █ █░▀█ ▄█

plugin {
    hyprbars {
        bar_height = 42
        bar_color = rgba(141b1eff)
        bar_padding = 20
        bar_blur = false
        bar_title_format = %i
        bar_title_enabled = false
        bar_text_font = JetBrainsMono Nerd Font
        bar_text_size = 12
        bar_buttons_alignment = left

        # macOS-style buttons: close, maximize, float
        hyprbars-button = rgb(ff5f57), 18, , hyprctl dispatch killactive
        hyprbars-button = rgb(febc2e), 18, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(28c840), 18, , hyprctl dispatch togglefloating
    }

    hyprexpo {
        columns = 4
        gap_size = 20
        gap_size_outer = 0
        bg_col = rgb(111111)
        workspace_method = center current
        gesture_distance = 300
        border_width = 0
        border_color_current = none
        border_color_hover = none
        border_color_focus = none
        window_icon_enable = true
        window_icon_position = bottom-right
        label_enable = false
        label_text_mode = token
        selection_label_enable = false
        selection_label_token_map = a,s,d,f,g,q,w,e,r,t,z,x,c,v,b
    }

    hyprscrolling {
        column_width = 0.7
        fullscreen_on_one_column = false
    }
}
