tab_bar_style custom
tab_bar_custom_draw ~/.config/kitty/tab_bar.py
tab_bar_min_tabs 1

tab_title_font_size 22
# tab_title_font_family JetBrains Mono Nerd Font
tab_title_font_family Iosevka Nerd Font

tab_bar_margin_width 2
tab_bar_margin_height 5

tab_bar_align left
tab_bar_edge bottom

tab_bar_margin_width 12.0
tab_bar_margin_height 10.0 10.0



