general {
    disable_loading_bar = true
    hide_cursor         = false
    grace               = 0
    no_fade_in          = false
    no_fade_out         = false
    ignore_empty_input  = false
    text_trim           = true
}

background {
    monitor     =
    path        = /home/ligichi/.config/hypr/assets/images/hyprlock-bg.png
    blur_passes = 0
    blur_size   = 0
    brightness  = 0.50
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"
    color = rgba(255, 255, 255, 1.0)
    font_size = 12
    font_family = Cinzel
    position = 100, 320
    halign = left
    valign = bottom
}


label {
    monitor     =
    text        = $USER
    color       = rgba(fdfaf2ff)
    font_size   = 24
    font_family = Cinzel
    position    = 100, 445
    halign      = left
    valign      = bottom
    shadow_passes = 0
    shadow_color  = rgba(00000099)
    shadow_size   = 0
}

label {
    monitor =
    text = $TIME
    font_size = 100
    font_family = Cinzel
    position = 100, 300 
    halign = left
    valign = bottom

}

label {
    monitor   =
    text      = ───   ✦   ───
    color     = rgba(c9a06366)
    font_size = 20
    position  = 100, 150
    halign    = left
    valign    = bottom
}

input-field {
    monitor  =
    size     = 100, 50
    outline_thickness = 0
    outer_color       = rgba(00000000)
    inner_color       = rgba(00000000)
    dots_text_format  = ✦
    dots_size         = 0.28
    dots_spacing      = 0.45
    dots_center       = false
    dots_rounding     = -1
    dot_color         = rgba(fdfaf244)
    font_color  = rgba(fdfaf2ff)
    font_size   = 20
    font_family = Cinzel
    fade_on_empty    = false
    placeholder_text = W A I T I N G   F O R   P A S S W O R D
    rounding        = 0
    check_color     = rgba(c9a063ff)
    fail_color      = rgba(ff4444ff)
    fail_text       = A C C E S S   D E N I E D
    fail_timeout    = 2000
    fail_transition = 300
    invert_numlock  = false
    swap_font_color = false
    position = 100, 100
    halign   = left
    valign   = bottom
}

# ── Bottom left ──────────────────────────────────────────────────
label {
    monitor     =
    text        = H Y P R L A N D
    color       = rgba(fdfaf2cc)
    font_size   = 18
    font_family = Cinzel
    position    = 100, 260
    halign      = left
    valign      = bottom
}

label {
    monitor     =
    text        = There is no such thing as fortune.  Try again.
    color       = rgba(fdfaf233)
    font_size   = 14
    font_family = ~/.config/hypr/assets/fonts/Cinzel-Bold.ttf
    position    = 100, 230
    halign      = left
    valign      = bottom
}

label {
    monitor     =
    text        = REBOOT    |    SHUTDOWN
    color       = rgba(fdfaf266)
    font_size   = 12
    font_family = ~/.config/hypr/assets/fonts/Cinzel-Bold.ttf
    position    = 100, 200
    halign      = left
    valign      = bottom
}


